BilgeAdam.MVC.Practice/Models/ErrorViewModel.cs
namespace BilgeAdam.MVC.Practice.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BilgeAdam.MVC.Practice/Components/CategoryViewComponent.cs
using BilgeAdam.Data;
using Microsoft.AspNetCore.Mvc;

namespace BilgeAdam.MVC.Practice.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private readonly NorthwindDbContext dbContext;

        public CategoryViewComponent(NorthwindDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            var result = dbContext.Categories.ToList();
            return View(result);
        }
    }
}

BilgeAdam.MVC.Practice/Components/CustomerViewComponent.cs
using BilgeAdam.Data;
using Microsoft.AspNetCore.Mvc;

namespace BilgeAdam.MVC.Practice.Components
{
    public class CustomerViewComponent:ViewComponent
    {
        private readonly NorthwindDbContext dbContext;

        public CustomerViewComponent(NorthwindDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            var result = dbContext.Customers.ToList();
            return View(result);
        }
    }
}

BilgeAdam.MVC.Practice/Components/ProductViewComponent.cs
using BilgeAdam.Data;
using Microsoft.AspNetCore.Mvc;

namespace BilgeAdam.MVC.Practice.Components
{
    public class ProductViewComponent : ViewComponent
    {
        private readonly NorthwindDbContext dbContext;

        public ProductViewComponent(NorthwindDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            var result = dbContext.Products.OrderByDescending(p=>p.ProductID).Take(10).ToList();
         
            return View(result);
        }
    }
}

BilgeAdam.MVC.Practice/Controllers/AdminController.cs
using BilgeAdam.Common.Dtos.Category;
using BilgeAdam.Common.Dtos.Customer;
using BilgeAdam.Common.Dtos.Product;
using BilgeAdam.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace BilgeAdam.MVC.Practice.Controllers
{
    public class AdminController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;
        private readonly ICustomerService customerService;

        public AdminController(IProductService productService,ICategoryService categoryService, ICustomerService customerService)
        {
            this.productService = productService;
            this.categoryService = categoryService;
            this.customerService = customerService;           
        }
      
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Product()
        {
            return View();
        }
        public IActionResult Category()
        {
            return View();
        }
        public IActionResult Customer()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(ProductAddDto input)
        {
            
            if (ModelState.IsValid)
            {
                productService.Add(input);
                return RedirectToAction("Product");
            }
            return View(input);
          
        }
        public IActionResult Delete(int id)
        {
           productService.Delete(id);
           return RedirectToAction("Product");

        }
        [HttpPost]
        public IActionResult CreateCategory(CategoryAddDto input)
        {

            if (ModelState.IsValid)
            {
                categoryService.AddCategory(input);
                return RedirectToAction("Category");
            }
            return View(input);

        }
        public IActionResult DeleteCategory(int id)
        {
            categoryService.DeleteCategory(id);
            return RedirectToAction("Category");

        }
        [HttpPost]
        public IActionResult CreateCustomer(CustomerAddDto input)
        {

            if (ModelState.IsValid)
            {
                customerService.AddCustomer(input);
                return RedirectToAction("Customer");
            }
            return View(input);

        }
        public IActionResult DeleteCustomer(string id)
        {
            customerService.DeleteCustomer(id);
            return RedirectToAction("Customer");

        }
    }
}

BilgeAdam.MVC.Practice/Controllers/HomeController.cs
using BilgeAdam.Common.Dtos.Product;
using BilgeAdam.Data;
using BilgeAdam.Data.Entities;
using BilgeAdam.MVC.Practice.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BilgeAdam.MVC.Practice.Controllers
{
    public class HomeController : Controller
    {
        private readonly NorthwindDbContext dbContext;

        public HomeController(NorthwindDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index(Category category)
        {
            var result = new List<ProductViewDto>();
            if (category.CategoryID != 0)
            {
                result = dbContext.Products.OrderByDescending(x => x.ProductID).Where(x => x.CategoryID == category.CategoryID).Select(p => new ProductViewDto
                {
                    Id = p.ProductID,
                    Name = p.ProductName,
                    Price = p.UnitPrice == null ? 0 : p.UnitPrice.Value,
                    Stock = p.UnitsInStock == null ? 0 : p.UnitsInStock.Value,
                }).Take(6).ToList();
            }
            else
            {
                result = dbContext.Products.OrderByDescending(x => x.ProductID).Select(p => new ProductViewDto
                {
                    Id = p.ProductID,
                    Name = p.ProductName,
                    Price = p.UnitPrice == null ? 0 : p.UnitPrice.Value,
                    Stock = p.UnitsInStock == null ? 0 : p.UnitsInStock.Value,
                }).Take(6).ToList();
            }
            ViewBag.title = category.CategoryName;
            return View(result);
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var result = dbContext.Products.Where(p => p.ProductID == id).Select(p => new ProductDetailDto
            {
                Id = p.ProductID,
                CategoryName = p.Category.CategoryName,
                CompanyName = p.Supplier.CompanyName,
                Name = p.ProductName,
                Order = p.UnitsOnOrder == null ? 0 : p.UnitsOnOrder.Value,
                Price = p.UnitPrice == null ? 0 : p.UnitPrice.Value,
                Quantity = p.QuantityPerUnit,
                Stock = p.UnitsInStock == null ? 0 : p.UnitsInStock.Value,
                SupplierContactName = p.Supplier.ContactName
            }).FirstOrDefault();
            return View(result);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Admin()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BilgeAdam.MVC.Practice/Views/Admin/Category.cshtml
@{
    ViewData["title"] = "Ürün Yönetim Paneli";
    Layout = "_AdminLayout";
}
@model CategoryAddDto
<div class="row">
    <div class="col-4">
        <form asp-action="CreateCategory" method="post">
    @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
    <div class="form-group">
        <label for="Name">Ürün Adı</label>
        <input type="text" id="Name" class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
   
    <div class="form-group">
        <label for="Description">Ürün Açıklama</label>
        <input type="text" id="Description" class="form-control" asp-for="Description" />
    </div>
    <button class="btn btn-primary float-end mt-3 w-25" type="submit">Kaydet</button>
</form>
    </div>
    <div class="col-8">

          @await Component.InvokeAsync("Category")
    </div>
</div>


@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
 } @*partial ile cshtml i inject ettik*@
}

BilgeAdam.MVC.Practice/Views/Admin/Customer.cshtml
@{
    ViewData["title"] = "Ürün Yönetim Paneli";
    Layout = "_AdminLayout";
}
@model CustomerAddDto
<div class="row">
    <div class="col-4">
        <form asp-action="CreateCustomer" method="post">
    @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
    <div class="form-group">
        <label for="Name">Şirket Adı</label>
        <input type="text" id="Name" class="form-control" asp-for="CustomerName" />
        <span asp-validation-for="CustomerName" class="text-danger"></span>
    </div>
   
    <div class="form-group">
        <label for="Description">Yetkili kişi</label>
        <input type="text" id="Description" class="form-control" asp-for="ContactName" />
    </div>
      <div class="form-group">
        <label for="Address">Adres</label>
        <input type="text" id="Address" class="form-control" asp-for="Address" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
      <div class="form-group">
        <label for="Phone">Telefon no</label>
        <input type="text" id="Phone" class="form-control" asp-for="Phone" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>
      <div class="form-group">
        <label for="CustomerId">Müşteri Numarası</label>
        <input type="text" id="CustomerId" class="form-control" asp-for="CustomerId" />
        <span asp-validation-for="CustomerId" class="text-danger"></span>
    </div>
    <button class="btn btn-primary float-end mt-3 w-25" type="submit">Kaydet</button>
</form>
    </div>
    <div class="col-8">

          @await Component.InvokeAsync("Customer")
    </div>
</div>


@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
 } @*partial ile cshtml i inject ettik*@
}

BilgeAdam.MVC.Practice/Views/Admin/Index.cshtml
@{
    Layout = "_AdminLayout";
}

BilgeAdam.MVC.Practice/Views/Admin/Product.cshtml
@{
    ViewData["title"] = "Ürün Yönetim Paneli";
    Layout = "_AdminLayout";
}
@model ProductAddDto
<div class="row">
    <div class="col-4">
        <form asp-action="Create" method="post">
    @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
    <div class="form-group">
        <label for="Name">Ürün Adı</label>
        <input type="text" id="Name" class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Price">Ürün Fiyatı</label>
        <input type="text" id="Price" class="form-control" asp-for="Price" />
    </div>
    <div class="form-group">
        <label for="Stock">Ürün Stok Bilgisi</label>
        <input type="text" id="Stock" class="form-control" asp-for="Stock" />
    </div>
    <button class="btn btn-primary float-end mt-3 w-25" type="submit">Kaydet</button>
</form>
    </div>
    <div class="col-8">
          @await Component.InvokeAsync("Product")
    </div>
</div>


@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
 } @*partial ile cshtml i inject ettik*@
}

BilgeAdam.MVC.Practice/Views/Home/Detail.cshtml
@{
    ViewData["Title"] = @Model.Name;
}
@model ProductDetailDto
<div class="row">
    <div class="col-4 shadow rounded-2 text-center">
        <img src="/images/@(Model.Id).jpg" />
    </div>
    <div class="col-8">
        <h1 class="text-warning">@Model.CompanyName</h1>
        <h3 class="text-center">Özellikler</h3>
        <div class="card">
            <table class="m-5">
                <tr>
                    <th class="text-danger">
                        Ürün Adı
                    </th>
                    <td >
                        @Model.Name
                    </td>
                </tr>
                <tr>
                    <th class="text-danger">
                        Kutu İçeriği 
                    </th>
                    <td>
                        @Model.Quantity
                    </td>
                </tr>
                <tr>
                    <th class="text-danger">
                        Stok Bilgisi
                    </th>
                    <td>
                        @Model.Stock
                    </td>
                </tr>
                <tr>
                    <th class="text-danger">
                        Şuan Siparişte Olanlar 
                    </th>
                    <td>
                        @Model.Order
                    </td>
                </tr>
                <tr>
                    <th class="text-danger">
                        Tedarikçi Şirket 
                    </th>
                    <td>
                        @Model.CompanyName
                    </td>
                </tr>
                <tr>
                    <th class="text-danger">
                        Tedarikçi Temsilcisi
                    </th>
                    <td>
                        @Model.SupplierContactName
                    </td>
                </tr>
                <tr>
                    <th class="text-danger">
                        Fiyat
                    </th>
                    <td class="fw-bold text-warning display-4">
                        @(decimal.Round(Model.Price, 2)) ₺
                    </td>
                </tr>
            </table>
            
        </div>
        <div>
            <button class="btn btn-success float-end mt-2 w-25">Sepete Ekle</button>
        </div>
    </div>
</div>

@section Styles{
    <style>

    </style>
}

BilgeAdam.MVC.Practice/Views/Home/Index.cshtml
@{
    ViewData["Title"] = @ViewBag.title;
}
@model List<ProductViewDto>
<div class="row">
    <h2 class="text-warning">@ViewBag.title</h2>
    @foreach (var product in @Model)
    {
        <div class="col-md-4 col-sm-6">
            <div class="card mt-4">
                <div class="image-container">
                    <div class="first">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="discount">-25%</span>
                            <span class="wishlist"><i class="fa fa-heart-o"></i></span>
                        </div>
                    </div>
                    @*href="/Home/Detail/@product.Id"*@
                    <a asp-action="Detail" asp-controller="Home" asp-route-id="@product.Id">
                        <img src="./images/@(product.Id).jpg" class="img-fluid rounded thumbnail-image">
                    </a>
                </div>
                <div class="product-detail-container p-2">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="dress-name">@product.Name</h5>
                        <div class="d-flex flex-column mb-2">
                            <span class="new-price">$@decimal.Round(product.Price, 2)</span>
                            <small class="old-price text-right">$@(decimal.Round(product.Price, 2)+5.99M)</small>
                        </div>
                    </div>
                    <div class="d-flex justify-content-between align-items-center pt-1">
                        <div class="color-select d-flex ">
                            <input type="button" name="grey" class="btn creme">
                            <input type="button" name="red" class="btn red ml-2">
                            <input type="button" name="blue" class="btn blue ml-2">
                        </div>
                        <div class="d-flex ">
                            <span class="item-size mr-2 btn" type="button">S</span>
                            <span class="item-size mr-2 btn" type="button">M</span>
                            <span class="item-size btn" type="button">L</span>
                        </div>
                    </div>
                    <div class="d-flex justify-content-between align-items-center pt-1">
                        <div>
                            <i class="fa fa-star-o rating-star"></i>
                            <span class="rating-number">4.8</span>
                        </div>
                        <span class="buy">Stock: @product.Stock</span>
                    </div>
                </div>
            </div>
        </div>
    }

</div>
@section Styles{
<Link rel="stylesheet" href="~/css/product.css" />
}
@section Scripts{
<script>
</script>
}

BilgeAdam.MVC.Practice/Views/Shared/Components/Category/Default.cshtml
@model List<Category>

<div>
    <ul>
        @foreach (var category in @Model)
        {
            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button href="@Url.Action("Admin", "Category", @category)" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_@category.CategoryID" aria-expanded="false" aria-controls="collapseOne">
                            @category.CategoryName
                        </button>
                    </h2>
                    <div  id="collapse_@category.CategoryID" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            @category.Description
                        </div>
                    </div>
                </div>
            </div>


        }
    </ul>

</div>

BilgeAdam.MVC.Practice/Views/Shared/Components/Customer/Default.cshtml
@model List<Customer>

<div>
    <ul>
        @foreach (var customer in @Model)
        {
            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button href="@Url.Action("Admin", "Customer", @customer)" class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_@customer.CustomerID"  aria-expanded="false" aria-controls="collapseOne">
                            @customer.CompanyName
                        </button>
                    </h2>
                    <div id="collapse_@customer.CustomerID" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                        <div class="accordion-body">

                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>Şirket Adı</th>
                                        <th>Yetkili Adı
                                        <th>Adres</th>
                                        <th>Phone</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    <tr>
                                        <td>@customer.CompanyName</td>
                                        <td>@customer.ContactName</td>
                                        <td>@customer.Address</td>
                                        <td>@customer.Phone</td>
                                         <td>
                        <a class="btn btn-primary float-end mt-3 w-10" asp-controller="Admin" asp-action="DeleteCustomer" asp-route-id =@customer.CustomerID>Sil</a> 

                     
                    </td>
                                    </tr>

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>


        }
    </ul>

</div>

BilgeAdam.MVC.Practice/Views/Shared/Components/Product/Default.cshtml
@model List<Product>

<div>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Ürün Adı</th>
                <th>Türü</th>
                <th>Fiyat</th>
                <th>Stok</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.ProductName</td>
                    <td>@p.CategoryID</td>
                    <td>@p.UnitPrice</td>
                    <td>@p.UnitsInStock</td>
                    <td>
                        <a class="btn btn-primary float-end mt-3 w-10" asp-controller="Admin" asp-action="Delete" asp-route-id =@p.ProductID>Sil</a> 

                     
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

BilgeAdam.MVC.Practice/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoostStore-Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoostStore-Admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/Home/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="/Admin/Index">Yönetici Paneli</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="min-height: 85vh !important;">
        <main role="main" class="pb-3">
            <div class="row">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link" href="/Admin/Product">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Admin/Category">Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Admin/Customer">Customer</a>
                    </li>
                </ul>
            </div>
            <div class="row">
                <div >@RenderBody()</div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BilgeAdam.MVC.Practice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BilgeAdam.MVC.Practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoostStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoostStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Home/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Admin/Index">Yönetici Paneli</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="min-height: 85vh !important;">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-3">@await Component.InvokeAsync("Category")</div>
                <div class="col-9">@RenderBody()</div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BilgeAdam.MVC.Practice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>